name: Build

# Controls when the workflow will run
on:
  push:
# pull_request:

  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.9'
      - run: flutter config --enable-windows-desktop
      - run: flutter build windows
      - uses: actions/upload-artifact@v3
        with:
          name: windows
          path: build/windows/runner/Release

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.9'
      - run: flutter config --enable-macos-desktop
      - run: flutter build macos
      - uses: actions/upload-artifact@v3
        with:
          name: macos
          path: build/macos/Build/Products/Release/*.app

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.9'
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
      - run: flutter config --enable-linux-desktop
      - run: flutter build linux
      - uses: actions/upload-artifact@v3
        with:
          name: linux
          path: build/linux/x64/release/bundle
